### ISSUE TITLE
Hi, the FPS is very low in my ubuntu desktop

### ISSUE THREAD

**Issue by JimXu1989** [cortictechnology/hand_asl_recognition#2]
Hi, thanks for sharing the great work.
I run the hand_tracker_asl.py on my ubuntu desktop, with my oak-d PoE device, but the frame seems very very low,
The frame will be refresh a few seconds a time, how to improve this? 
Thanks a lot!

**Comment by michaelhwn** [comment]
HI @JimXu1989, sorry for the late reply, this project was written and tested on the Raspberry OS on a Raspberry Pi 4, although it should also run on a Ubuntu machine, the packages installed from the install_dependencies.sh may not be optimized on other machines. If you can give me the details of the machine you were running the demo on, I may be able to help figuring out why was it slow.

**Comment by JimXu1989** [comment]
> HI @JimXu1989, sorry for the late reply, this project was written and tested on the Raspberry OS on a Raspberry Pi 4, although it should also run on a Ubuntu machine, the packages installed from the install_dependencies.sh may not be optimized on other machines. If you can give me the details of the machine you were running the demo on, I may be able to help figuring out why was it slow.

Hi, nice to hear from you!
I use ubuntu 20.04, with a CUDA enable GPU. I have installed pytorch and so on.

**Comment by I-am-vishalmaurya** [comment]
Just had a small doubt can we use this repo to integrate with the web browser.

**Comment by michaelhwn** [comment]
> > HI @JimXu1989, sorry for the late reply, this project was written and tested on the Raspberry OS on a Raspberry Pi 4, although it should also run on a Ubuntu machine, the packages installed from the install_dependencies.sh may not be optimized on other machines. If you can give me the details of the machine you were running the demo on, I may be able to help figuring out why was it slow.
> 
> Hi, nice to hear from you! I use ubuntu 20.04, with a CUDA enable GPU. I have installed pytorch and so on.

I see, hardware-wise, I think your computer hardware should be more than enough to run this project. I don't currently have an OAK-D POE device for testing, but I have tested with an OAK-D on a computer with similar setup as yours, and the speed seems normal. I would suggest you try using the project with an OAK-D device for now.

**Comment by michaelhwn** [comment]
> Just had a small doubt can we use this repo to integrate with the web browser.

Hi, it would require some development work to port this project into the web browser. You are welcome to contribute to this and commit back to the project when you have a working version.
